/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KryptandTranslate {
    }
    interface KryptandTranslationProvider {
    }
}
declare global {
    interface HTMLKryptandTranslateElement extends Components.KryptandTranslate, HTMLStencilElement {
    }
    var HTMLKryptandTranslateElement: {
        prototype: HTMLKryptandTranslateElement;
        new (): HTMLKryptandTranslateElement;
    };
    interface HTMLKryptandTranslationProviderElement extends Components.KryptandTranslationProvider, HTMLStencilElement {
    }
    var HTMLKryptandTranslationProviderElement: {
        prototype: HTMLKryptandTranslationProviderElement;
        new (): HTMLKryptandTranslationProviderElement;
    };
    interface HTMLElementTagNameMap {
        "kryptand-translate": HTMLKryptandTranslateElement;
        "kryptand-translation-provider": HTMLKryptandTranslationProviderElement;
    }
}
declare namespace LocalJSX {
    interface KryptandTranslate {
    }
    interface KryptandTranslationProvider {
    }
    interface IntrinsicElements {
        "kryptand-translate": KryptandTranslate;
        "kryptand-translation-provider": KryptandTranslationProvider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kryptand-translate": LocalJSX.KryptandTranslate & JSXBase.HTMLAttributes<HTMLKryptandTranslateElement>;
            "kryptand-translation-provider": LocalJSX.KryptandTranslationProvider & JSXBase.HTMLAttributes<HTMLKryptandTranslationProviderElement>;
        }
    }
}
